;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname p3-fs) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(define authors-1 (list "hilbert" "heisenberg" "h" "hello"))
(define authors-2 '())
(define authors-3 (list "bad" "generally" "good" "great"))
(define authors-4 (list "generally" "good" "bad" "great"))

(check-expect (fix-shelves '()) '())
(check-expect (fix-shelves (list (make-shelf #\h authors-1))) '())
(check-expect (fix-shelves (list (make-shelf #\t authors-1))) (list (make-shelf #\t authors-1)))
(check-expect (fix-shelves (list
                            (make-shelf #\h authors-1)
                            (make-shelf #\t authors-1)
                            (make-shelf #\h authors-2)
                            (make-shelf #\t authors-2)
                            (make-shelf #\b authors-3)
                            (make-shelf #\g authors-3)
                            (make-shelf #\h authors-4)
                            (make-shelf #\g authors-4)))
              (list (make-shelf #\t authors-1)
                    (make-shelf #\b (list "generally" "good" "great"))
                    (make-shelf #\g (list "bad"))
                    (make-shelf #\h authors-4)
                    (make-shelf #\g (list "bad"))))
(check-expect (fix-shelves (list (make-shelf #\g authors-4)
                                 (make-shelf #\g authors-4)
                                 (make-shelf #\g authors-4)))
              (list (make-shelf #\g (list "bad"))
                    (make-shelf #\g (list "bad"))
                    (make-shelf #\g (list "bad"))))