;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname p4-vf) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
(define fish-1 (make-fish "Bass" 10))
(define fish-2 (make-fish "Bass" 8))
(define fish-3 (make-fish "Bass" 6))
(define fish-4 (make-fish "Sunfish" 10000))
(define fish-5 (make-fish "Sunfish" 1000))
(define fish-6 (make-fish "Sunfish" 100))
(define fish-7 (make-fish "25519 {} !@#$%^&*()" 8.01))
(define fish-8 (make-fish "25519 {} !@#$%^&*()" -9))

(check-expect (viable-fish '() '()) '())
(check-expect (viable-fish '() (list "Bass" "Sunfish" "25519 {} !@#$%^&*()" "Word")) '())
(check-expect (viable-fish (list fish-1 fish-2 fish-3 fish-4 fish-5 fish-6 fish-7 fish-8) '())
              (list fish-1 fish-4 fish-5 fish-6 fish-7))
(check-expect (viable-fish (list fish-1 fish-8 fish-2 fish-7 fish-3 fish-6 fish-4 fish-5)
                           (list "Bass"))
              (list fish-7 fish-6 fish-4 fish-5))
(check-expect (viable-fish (list fish-1 fish-8 fish-2 fish-7 fish-3 fish-6 fish-4 fish-5)
                           (list "25519 {} !@#$%^&*()" "Sunfish"))
              (list fish-1))
(check-expect (viable-fish (list fish-1 fish-8 fish-2 fish-7 fish-3 fish-6 fish-4 fish-5)
                           (list "25519 {} !@#$%^&*()" "Bass" "Sunfish"))
              '())
(check-expect (viable-fish (list fish-1 fish-1 fish-1 fish-2 fish-1 fish-4 fish-1 fish-7)
                           (list "25519 {} !@#$%^&*()"))
              (list fish-1 fish-1 fish-1 fish-1 fish-4 fish-1))